services:
  registros-historicos-productor:
    image: ms-registros-historicos-productor
    container_name: registros-historicos-productor
    ports:
      - "8083:8083"
    environment:
      SPRING_RABBITMQ_HOST: "50.17.240.116"
      SPRING_RABBITMQ_PORT: "5672"
      SPRING_RABBITMQ_USERNAME: "admin"
      SPRING_RABBITMQ_PASSWORD: "usuarioec2"
      RABBITMQ_EXCHANGE_ALERTAS: "alertas_medicas_exchange"
      SPRING_RABBITMQ_QUEUE: "registros_historicos_queue"
      RABBITMQ_ROUTINGKEY_ALERTAS: "registros_historicos_key"
    restart: always
    networks:
      - kafka_kafka-net 

networks:
  kafka_kafka-net:
    external: true
